parameters:
#    coregen_user.example.class: Coregen\UserBundle\Example

services:
#    coregen_user.example:
#        class: %coregen_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
